# Generated by Django 5.2.5 on 2025-11-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
