# Generated by Django 5.2.5 on 2025-11-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='images/Pythoneros_pfp1_proj_final.png', max_length=255),
        ),
    ]
