# Generated by Django 5.2.5 on 2025-11-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_desc', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('day', models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miercoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Saturday'), ('SUN', 'Domingo')], max_length=10)),
                ('hour', models.CharField(max_length=5)),
                ('half', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day', 'hour', 'half')},
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
