# Generated by Django 5.2.5 on 2025-11-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_schedule_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='colorpreference',
            field=models.TextField(default='tema-a', max_length=6),
        ),
    ]
