# Generated by Django 5.2.5 on 2025-11-15 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_user_notes_delete_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHomeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuadrante1', models.CharField(blank=True, max_length=200, null=True)),
                ('cuadrante2', models.CharField(blank=True, max_length=200, null=True)),
                ('cuadrante3', models.CharField(blank=True, max_length=200, null=True)),
                ('cuadrante4', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
