# Generated by Django 5.2.5 on 2025-11-15 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_userhomelayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHomeLayout',
            new_name='UserLayout',
        ),
    ]
