# Generated by Django 5.2.5 on 2025-11-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_rename_userhomelayout_userlayout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLayout',
        ),
    ]
